In [1]:
import numpy as np
import monai
import torch

In [53]:
#3d segmentation metrics

# size = (batch, c, h, w, d)
seg_original = torch.randint(0, 2, size=(16, 2, 32, 32, 32))
seg_prediction = torch.randint(0, 2, size=(16, 2, 32, 32, 32))

In [54]:
# average symmetric surface distance (direct computation)
result = monai.metrics.compute_average_surface_distance(seg_prediction, seg_original, include_background=False, symmetric=True, distance_metric="euclidean")

In [55]:
result_reverse = monai.metrics.compute_average_surface_distance(seg_original, seg_prediction, include_background=False, symmetric=True, distance_metric="euclidean")

In [56]:
print(result)
print(result.shape)

tensor([[0.5077],
        [0.5089],
        [0.5145],
        [0.5101],
        [0.5060],
        [0.5052],
        [0.5139],
        [0.5097],
        [0.5165],
        [0.5109],
        [0.5108],
        [0.5097],
        [0.5088],
        [0.5048],
        [0.5089],
        [0.5078]], dtype=torch.float64)
torch.Size([16, 1])


In [57]:
print(result_reverse)
print(result_reverse.shape)
print((result == result_reverse).all())

tensor([[0.5077],
        [0.5089],
        [0.5145],
        [0.5101],
        [0.5060],
        [0.5052],
        [0.5139],
        [0.5097],
        [0.5165],
        [0.5109],
        [0.5108],
        [0.5097],
        [0.5088],
        [0.5048],
        [0.5089],
        [0.5078]], dtype=torch.float64)
torch.Size([16, 1])
tensor(True)


In [58]:
# average symmetric surface distance (function-based organization)
ASSD = monai.metrics.SurfaceDistanceMetric(include_background=False, symmetric=True, distance_metric="euclidean")

In [59]:
tensor_ASSD = ASSD(seg_prediction, seg_original)

In [60]:
print(tensor_ASSD)

tensor([[0.5077],
        [0.5089],
        [0.5145],
        [0.5101],
        [0.5060],
        [0.5052],
        [0.5139],
        [0.5097],
        [0.5165],
        [0.5109],
        [0.5108],
        [0.5097],
        [0.5088],
        [0.5048],
        [0.5089],
        [0.5078]], dtype=torch.float64)


In [66]:
# Mean Dice (direct computation)
dice_result = monai.metrics.compute_meandice(seg_prediction, seg_original, include_background=False)

In [70]:
print(dice_result)
print(dice_result.shape)

tensor([[0.5027],
        [0.5015],
        [0.4955],
        [0.5008],
        [0.5037],
        [0.5048],
        [0.4966],
        [0.4995],
        [0.4935],
        [0.4982],
        [0.5009],
        [0.4992],
        [0.5017],
        [0.5045],
        [0.5012],
        [0.5022]])
torch.Size([16, 1])


In [73]:
# Mean Dice (function-based organization)
DICE = monai.metrics.DiceMetric(include_background=False)

In [75]:
tensor_dice = DICE(seg_prediction, seg_original)

In [76]:
print(tesnor_dice)

tensor([[0.5027],
        [0.5015],
        [0.4955],
        [0.5008],
        [0.5037],
        [0.5048],
        [0.4966],
        [0.4995],
        [0.4935],
        [0.4982],
        [0.5009],
        [0.4992],
        [0.5017],
        [0.5045],
        [0.5012],
        [0.5022]])


In [77]:
# 참고하시면 될 것 같아요.

def dice(prediction, label):
    '''
    prediction: (batch, c, h, w, d)
    label: (batch, c, h, w, d)
    
    output: (batch, 1)
    '''
    output = monai.metrics.compute_meandice(prediction, label, include_background=False)
    
    return output.to("cpu").numpy()

def assd(prediction, label):
    '''
    prediction: (batch, c, h, w, d)
    label: (batch, c, h, w, d)
    
    (batch, 1)
    '''
    output = monai.metrics.compute_average_surface_distance(prediction, label, include_background=False, symmetric=True, distance_metric="euclidean")
        
    return output.to("cpu").numpy()


In [78]:
dice(seg_prediction, seg_original)

array([[0.50268686],
       [0.5014791 ],
       [0.49552312],
       [0.5008258 ],
       [0.5036776 ],
       [0.504795  ],
       [0.49660447],
       [0.49947032],
       [0.49349293],
       [0.49817228],
       [0.5009143 ],
       [0.49915826],
       [0.50171006],
       [0.5044886 ],
       [0.5012339 ],
       [0.50217134]], dtype=float32)

In [79]:
assd(seg_prediction, seg_original)

array([[0.50769641],
       [0.50888428],
       [0.51448902],
       [0.51014245],
       [0.50600171],
       [0.50515939],
       [0.51390931],
       [0.50970582],
       [0.5164664 ],
       [0.5109139 ],
       [0.51082624],
       [0.50965082],
       [0.50879002],
       [0.5047586 ],
       [0.50888982],
       [0.50782911]])